name: Build

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  tests:
    name: Lint, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .

      - name: Test with Pytest
        run: |
          pytest --cov=src --cov-report=xml:coverage.xml --cov-report term-missing

      - name: Prepare coverage report for SonarCloud
        run: |
          sed -i 's|/home/runner/work/open-core/open-core/src|src|g' coverage.xml

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: Build the distribution package
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload the distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs:
      - tests
      - build
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download all the release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Sign the distribution package with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create '${{ github.ref_name }}' \
          --repo '${{ github.repository }}' \
          --notes ""