name: Test

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint
    runs-on: fedora-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .

  test:
    name: Test
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [fedora-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up ${{ matrix.os }} with Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests with Pytest
        run: |
          pytest --cov=. --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-${{ matrix.os }}-${{ matrix.python-version }}
          path: coverage.xml

  analyze:
    name: Analyze
    needs: test
    runs-on: fedora-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download coverage reports
        uses: actions/download-artifact@v3
        with:
          name: coverage-report-*
          path: coverage-reports/

      - name: Combine coverage reports
        run: |
          pip install coverage
          coverage combine coverage-reports/*/coverage.xml
          coverage xml -o coverage_combined.xml

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dsonar.python.coverage.reportPaths=coverage_combined.xml

  auto-merge:
    name: Auto Merge
    needs: [lint, test, analyze]
    runs-on: fedora-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Merge Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { context, github } = require('@actions/github');
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'  # or 'merge' or 'rebase'
            });